[package]
name = "understanding_package_and_crates"
version = "0.1.0"
edition = "2021"

[dependencies]
grouping_related_code_in_modules = {path = "/home/sonynurdianto/Project/RustLearning/grouping_related_code_in_modules"}
