[package]
name = "s3_image_handle"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = "1.5.0"
leptos = { version = "0.6.15", features = ["csr"] }
tokio = { version = "1.41.1", features = ["full", "mio", "test-util", "tracing", "windows-sys"] }
web-sys = "0.3.72"
