[package]
name = "load_async_transition_6_3"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-timers = { version = "0.3.0", features = ["futures"] }
leptos = { version = "0.6.15", features = ["csr"] }
