[package]
name = "curriosity_visual_1"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6.15", features = ["csr"] }
plotters = "0.3.7"
plotters-canvas = "0.3.0"
wasm-bindgen = "0.2.95"
